//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM4MServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Name="Authentication Web ServiceSoap", Namespace="http://webportalbridge.ptassoc.com/Authentication/", ConfigurationName="CRM4MServiceReference.AuthenticationWebServiceSoap")]
    public interface AuthenticationWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/AuthenticateToken", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateTokenResponse> AuthenticateTokenAsync(CRM4MServiceReference.AuthenticateTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateUserResponse> AuthenticateUserAsync(CRM4MServiceReference.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/AuthenticateUserWithoutPWD", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateUserWithoutPWDResponse> AuthenticateUserWithoutPWDAsync(CRM4MServiceReference.AuthenticateUserWithoutPWDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/DeleteUserSession", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM4MServiceReference.DeleteUserSessionResponse> DeleteUserSessionAsync(CRM4MServiceReference.DeleteUserSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/GetContactByFilter", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM4MServiceReference.GetContactByFilterResponse> GetContactByFilterAsync(CRM4MServiceReference.GetContactByFilterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/ValidateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM4MServiceReference.ValidateUserResponse> ValidateUserAsync(CRM4MServiceReference.ValidateUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateToken", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.AuthenticateTokenRequestBody Body;
        
        public AuthenticateTokenRequest()
        {
        }
        
        public AuthenticateTokenRequest(CRM4MServiceReference.AuthenticateTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public AuthenticateTokenRequestBody()
        {
        }
        
        public AuthenticateTokenRequestBody(string securityPassword, string token)
        {
            this.securityPassword = securityPassword;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateTokenResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.AuthenticateTokenResponseBody Body;
        
        public AuthenticateTokenResponse()
        {
        }
        
        public AuthenticateTokenResponse(CRM4MServiceReference.AuthenticateTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateTokenResult;
        
        public AuthenticateTokenResponseBody()
        {
        }
        
        public AuthenticateTokenResponseBody(string AuthenticateTokenResult)
        {
            this.AuthenticateTokenResult = AuthenticateTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest()
        {
        }
        
        public AuthenticateUserRequest(CRM4MServiceReference.AuthenticateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public AuthenticateUserRequestBody()
        {
        }
        
        public AuthenticateUserRequestBody(string securityPassword, string username, string password)
        {
            this.securityPassword = securityPassword;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse()
        {
        }
        
        public AuthenticateUserResponse(CRM4MServiceReference.AuthenticateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponseBody()
        {
        }
        
        public AuthenticateUserResponseBody(string AuthenticateUserResult)
        {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWithoutPWDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWithoutPWD", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.AuthenticateUserWithoutPWDRequestBody Body;
        
        public AuthenticateUserWithoutPWDRequest()
        {
        }
        
        public AuthenticateUserWithoutPWDRequest(CRM4MServiceReference.AuthenticateUserWithoutPWDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateUserWithoutPWDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        public AuthenticateUserWithoutPWDRequestBody()
        {
        }
        
        public AuthenticateUserWithoutPWDRequestBody(string securityPassword, string username)
        {
            this.securityPassword = securityPassword;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWithoutPWDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWithoutPWDResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.AuthenticateUserWithoutPWDResponseBody Body;
        
        public AuthenticateUserWithoutPWDResponse()
        {
        }
        
        public AuthenticateUserWithoutPWDResponse(CRM4MServiceReference.AuthenticateUserWithoutPWDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateUserWithoutPWDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateUserWithoutPWDResult;
        
        public AuthenticateUserWithoutPWDResponseBody()
        {
        }
        
        public AuthenticateUserWithoutPWDResponseBody(string AuthenticateUserWithoutPWDResult)
        {
            this.AuthenticateUserWithoutPWDResult = AuthenticateUserWithoutPWDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserSession", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.DeleteUserSessionRequestBody Body;
        
        public DeleteUserSessionRequest()
        {
        }
        
        public DeleteUserSessionRequest(CRM4MServiceReference.DeleteUserSessionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class DeleteUserSessionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public DeleteUserSessionRequestBody()
        {
        }
        
        public DeleteUserSessionRequestBody(string securityPassword, string token)
        {
            this.securityPassword = securityPassword;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserSessionResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.DeleteUserSessionResponseBody Body;
        
        public DeleteUserSessionResponse()
        {
        }
        
        public DeleteUserSessionResponse(CRM4MServiceReference.DeleteUserSessionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class DeleteUserSessionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteUserSessionResult;
        
        public DeleteUserSessionResponseBody()
        {
        }
        
        public DeleteUserSessionResponseBody(string DeleteUserSessionResult)
        {
            this.DeleteUserSessionResult = DeleteUserSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactByFilterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactByFilter", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.GetContactByFilterRequestBody Body;
        
        public GetContactByFilterRequest()
        {
        }
        
        public GetContactByFilterRequest(CRM4MServiceReference.GetContactByFilterRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class GetContactByFilterRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string value;
        
        public GetContactByFilterRequestBody()
        {
        }
        
        public GetContactByFilterRequestBody(string securityPassword, string filter, string value)
        {
            this.securityPassword = securityPassword;
            this.filter = filter;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactByFilterResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactByFilterResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.GetContactByFilterResponseBody Body;
        
        public GetContactByFilterResponse()
        {
        }
        
        public GetContactByFilterResponse(CRM4MServiceReference.GetContactByFilterResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class GetContactByFilterResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetContactByFilterResult;
        
        public GetContactByFilterResponseBody()
        {
        }
        
        public GetContactByFilterResponseBody(string GetContactByFilterResult)
        {
            this.GetContactByFilterResult = GetContactByFilterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.ValidateUserRequestBody Body;
        
        public ValidateUserRequest()
        {
        }
        
        public ValidateUserRequest(CRM4MServiceReference.ValidateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class ValidateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public ValidateUserRequestBody()
        {
        }
        
        public ValidateUserRequestBody(string securityPassword, string username, string password)
        {
            this.securityPassword = securityPassword;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public CRM4MServiceReference.ValidateUserResponseBody Body;
        
        public ValidateUserResponse()
        {
        }
        
        public ValidateUserResponse(CRM4MServiceReference.ValidateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class ValidateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateUserResult;
        
        public ValidateUserResponseBody()
        {
        }
        
        public ValidateUserResponseBody(string ValidateUserResult)
        {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface AuthenticationWebServiceSoapChannel : CRM4MServiceReference.AuthenticationWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AuthenticationWebServiceSoapClient : System.ServiceModel.ClientBase<CRM4MServiceReference.AuthenticationWebServiceSoap>, CRM4MServiceReference.AuthenticationWebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticationWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticationWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticationWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticationWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateTokenResponse> CRM4MServiceReference.AuthenticationWebServiceSoap.AuthenticateTokenAsync(CRM4MServiceReference.AuthenticateTokenRequest request)
        {
            return base.Channel.AuthenticateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateTokenResponse> AuthenticateTokenAsync(string securityPassword, string token)
        {
            CRM4MServiceReference.AuthenticateTokenRequest inValue = new CRM4MServiceReference.AuthenticateTokenRequest();
            inValue.Body = new CRM4MServiceReference.AuthenticateTokenRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.token = token;
            return ((CRM4MServiceReference.AuthenticationWebServiceSoap)(this)).AuthenticateTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateUserResponse> CRM4MServiceReference.AuthenticationWebServiceSoap.AuthenticateUserAsync(CRM4MServiceReference.AuthenticateUserRequest request)
        {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateUserResponse> AuthenticateUserAsync(string securityPassword, string username, string password)
        {
            CRM4MServiceReference.AuthenticateUserRequest inValue = new CRM4MServiceReference.AuthenticateUserRequest();
            inValue.Body = new CRM4MServiceReference.AuthenticateUserRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((CRM4MServiceReference.AuthenticationWebServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateUserWithoutPWDResponse> CRM4MServiceReference.AuthenticationWebServiceSoap.AuthenticateUserWithoutPWDAsync(CRM4MServiceReference.AuthenticateUserWithoutPWDRequest request)
        {
            return base.Channel.AuthenticateUserWithoutPWDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM4MServiceReference.AuthenticateUserWithoutPWDResponse> AuthenticateUserWithoutPWDAsync(string securityPassword, string username)
        {
            CRM4MServiceReference.AuthenticateUserWithoutPWDRequest inValue = new CRM4MServiceReference.AuthenticateUserWithoutPWDRequest();
            inValue.Body = new CRM4MServiceReference.AuthenticateUserWithoutPWDRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.username = username;
            return ((CRM4MServiceReference.AuthenticationWebServiceSoap)(this)).AuthenticateUserWithoutPWDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM4MServiceReference.DeleteUserSessionResponse> CRM4MServiceReference.AuthenticationWebServiceSoap.DeleteUserSessionAsync(CRM4MServiceReference.DeleteUserSessionRequest request)
        {
            return base.Channel.DeleteUserSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM4MServiceReference.DeleteUserSessionResponse> DeleteUserSessionAsync(string securityPassword, string token)
        {
            CRM4MServiceReference.DeleteUserSessionRequest inValue = new CRM4MServiceReference.DeleteUserSessionRequest();
            inValue.Body = new CRM4MServiceReference.DeleteUserSessionRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.token = token;
            return ((CRM4MServiceReference.AuthenticationWebServiceSoap)(this)).DeleteUserSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM4MServiceReference.GetContactByFilterResponse> CRM4MServiceReference.AuthenticationWebServiceSoap.GetContactByFilterAsync(CRM4MServiceReference.GetContactByFilterRequest request)
        {
            return base.Channel.GetContactByFilterAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM4MServiceReference.GetContactByFilterResponse> GetContactByFilterAsync(string securityPassword, string filter, string value)
        {
            CRM4MServiceReference.GetContactByFilterRequest inValue = new CRM4MServiceReference.GetContactByFilterRequest();
            inValue.Body = new CRM4MServiceReference.GetContactByFilterRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.filter = filter;
            inValue.Body.value = value;
            return ((CRM4MServiceReference.AuthenticationWebServiceSoap)(this)).GetContactByFilterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM4MServiceReference.ValidateUserResponse> CRM4MServiceReference.AuthenticationWebServiceSoap.ValidateUserAsync(CRM4MServiceReference.ValidateUserRequest request)
        {
            return base.Channel.ValidateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM4MServiceReference.ValidateUserResponse> ValidateUserAsync(string securityPassword, string username, string password)
        {
            CRM4MServiceReference.ValidateUserRequest inValue = new CRM4MServiceReference.ValidateUserRequest();
            inValue.Body = new CRM4MServiceReference.ValidateUserRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((CRM4MServiceReference.AuthenticationWebServiceSoap)(this)).ValidateUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Authentication_x0020_Web_x0020_ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Authentication_x0020_Web_x0020_ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Authentication_x0020_Web_x0020_ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://cicstagednn1.pcbscloud.com/DesktopModules/MX/Authentication.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Authentication_x0020_Web_x0020_ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cicstagednn1.pcbscloud.com/DesktopModules/MX/Authentication.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Authentication_x0020_Web_x0020_ServiceSoap,
            
            Authentication_x0020_Web_x0020_ServiceSoap12,
        }
    }
}
